-- Generated by scripts/seed-guide.mjs from data/eateries.json — do not edit by hand.
-- Local food guide + the must-see ranking. Idempotent.

insert into public.eateries (slug, name, city, dishes, price_tier, is_splurge, maps_url, notes, sort_order)
values
  ('mui-xin-laksa', 'Mui Xin Laksa', 'Kuching', array['laksa']::text[], 1, false, 'https://maps.app.goo.gl/AC1NjSx1w39RLkEz5', null, 0),
  ('126-laksa', '126 Laksa', 'Kuching', array['laksa']::text[], 2, false, 'https://maps.app.goo.gl/nztN4B7dU8KwRPZS9', null, 1),
  ('shirley-traditional-kolo-mee', 'Shirley Traditional Kolo Mee', 'Kuching', array['kolo-mee']::text[], 1, false, 'https://maps.app.goo.gl/DBU3MiF1aW7i5moPA', null, 2),
  ('annie-kolo-mee', 'Annie Kolo Mee', 'Kuching', array['kolo-mee']::text[], 2, false, 'https://maps.app.goo.gl/fWd1NVpVsTtD3J9G9', null, 3),
  ('lepau', 'Lepau', 'Kuching', array['umai', 'manok-pansoh', 'midin']::text[], 3, false, 'https://maps.app.goo.gl/CaxHjgiPR6ute1JN9', 'One stop for umai, manok pansoh and midin.', 4),
  ('jak-maan', 'JAK MA''AN', 'Kuching', array['manok-pansoh']::text[], 2, false, 'https://maps.app.goo.gl/coaUaWEv5EtFYBPb6', null, 5),
  ('topspot-food-court', 'Topspot Food Court', 'Kuching', array['midin']::text[], 2, false, 'https://maps.app.goo.gl/kRb5nVEJ8GBSyY9M6', null, 6),
  ('kompia-house', 'Kompia House', 'Kuching', array['kompia']::text[], 1, false, 'https://maps.app.goo.gl/sWaqnz9jtbE5s8dX9', null, 7),
  ('dayang-salhah', 'Dayang Salhah', 'Kuching', array['kek-lapis']::text[], 1, false, 'https://maps.app.goo.gl/sVKhAhmMcnB6cYaw6', null, 8),
  ('kek-lapis-mama-su', 'Kek Lapis Mama Su', 'Kuching', array['kek-lapis']::text[], 2, false, 'https://maps.app.goo.gl/WDMU7Dt1Ew1ancE79', null, 9),
  ('kek-lapis-warisan', 'Kek Lapis Warisan', 'Kuching', array['kek-lapis']::text[], 3, false, 'https://maps.app.goo.gl/VPEgNAz9VE7kHVTN7', null, 10),
  ('roots-restaurant', 'ROOTS Restaurant', 'Kuching', array['fine-dining']::text[], 3, true, 'https://maps.app.goo.gl/gbKERWjGE2VR75fS7', null, 11),
  ('liang-yew-cafe', 'Liang Yew Cafe', 'Sibu', array['kampua']::text[], 1, false, 'https://maps.app.goo.gl/XVkn7t6qy3bvKB9R9', null, 12),
  ('noodle-house-laichee', 'Noodle House LaiChee', 'Sibu', array['kampua']::text[], 2, false, 'https://maps.app.goo.gl/YDwMvyyYHBTMVnPo8', null, 13),
  ('sheng-kee-63', 'Sheng Kee 63', 'Sibu', array['kompia']::text[], 1, false, 'https://maps.app.goo.gl/EBLMfVsnyKdZTtbv6', null, 14),
  ('fatt-bakery', 'Fatt Bakery', 'Sibu', array['kompia']::text[], 1, false, 'https://maps.app.goo.gl/E186PAcCrfSoQEFz9', null, 15),
  ('mak-borneo', 'Mak Borneo', 'Sibu', array['umai', 'manok-pansoh']::text[], 2, false, 'https://maps.app.goo.gl/xeTyhGszeSiAgRTR6', null, 16),
  ('hajijah-kek-lapis', 'Hajijah Kek Lapis', 'Sibu', array['kek-lapis']::text[], 1, false, 'https://maps.app.goo.gl/HQUFPis966gsBWod9', null, 17),
  ('mingziang-court', 'Mingziang Court', 'Sibu', array['fine-dining']::text[], null, true, 'https://maps.app.goo.gl/tSYHtsTwpvJnY9X59', 'Try the Empurau fish.', 18),
  ('a-mas-laksa', 'A Ma''s Laksa', 'Miri', array['laksa']::text[], 1, false, 'https://maps.app.goo.gl/EgHJXqxh5inv2BVE6', null, 19),
  ('laksa-lolita', 'Laksa Lolita', 'Miri', array['laksa']::text[], 1, false, 'https://maps.app.goo.gl/QzoBCTyanekgVPmZ9', null, 20),
  ('kebaya-story', 'Kebaya Story', 'Miri', array['laksa']::text[], 2, false, 'https://maps.app.goo.gl/5pwSege43g1bEmaY7', null, 21),
  ('mat-kolok', 'Mat Kolok', 'Miri', array['kolo-mee']::text[], 1, false, 'https://maps.app.goo.gl/KzuUgAq8pCzjAcCX6', null, 22),
  ('lapis-by-bebulak', 'LAPIS by Be''Bulak', 'Miri', array['kek-lapis']::text[], 2, false, 'https://maps.app.goo.gl/igmKW2enBKTMkZ257', 'Near the airport.', 23),
  ('cavakita-rooftop-bar', 'Cavakita Rooftop Bar', 'Miri', array['fine-dining']::text[], null, true, 'https://maps.app.goo.gl/za9KEUj7XCZETikc6', 'Go for the sunset.', 24),
  ('the-meld', 'THE MELD', 'Miri', array['fine-dining']::text[], null, true, 'https://maps.app.goo.gl/umane5Z4cwEWBhCH6', 'A romantic dinner.', 25),
  ('sumandapur-cafe', 'Sumandapur Cafe', 'Bintulu', array['laksa', 'umai', 'manok-pansoh']::text[], 2, false, 'https://maps.app.goo.gl/xZvAQHYdDuWpR2ye6', 'Laksa, umai and pansoh all in one place.', 26),
  ('ho-ga-pang-laksa', 'Ho Ga Pang Laksa', 'Bintulu', array['laksa']::text[], 1, false, 'https://maps.app.goo.gl/P6Uis4UEyuedApMk8', null, 27),
  ('153-kolo-mee', '153 Kolo Mee', 'Bintulu', array['kolo-mee']::text[], 1, false, 'https://maps.app.goo.gl/xxVchBL7kWJwX4Et8', null, 28),
  ('the-italian-fairfield', 'The Italian (Fairfield Marriott)', 'Bintulu', array['fine-dining']::text[], null, true, 'https://maps.app.goo.gl/Pn76C1wgcTMPa7Y6A', null, 29)
on conflict (slug) do update set
  name = excluded.name, city = excluded.city, dishes = excluded.dishes, price_tier = excluded.price_tier,
  is_splurge = excluded.is_splurge, maps_url = excluded.maps_url, notes = excluded.notes,
  sort_order = excluded.sort_order;

-- Must-see ranking (1-5 "must-see", 6-8 "also great"). Only rows that exist are ranked.
update public.attractions a
set featured_rank = v.rank
from (values
  ('semenggoh-nature-reserve', 1),
  ('gunung-mulu-national-park', 2),
  ('sarawak-cultural-village', 3),
  ('niah-caves', 4),
  ('bako-national-park', 5),
  ('kuching-waterfront', 6),
  ('lambir-hills-national-park', 7),
  ('kuching-wetlands', 8)
) as v(slug, rank)
where a.slug = v.slug;

-- Places the guide lists that we don't have full details for yet. Created as UNPUBLISHED drafts
-- with only what the guide says — an admin adds photos, price, hours and visit length, then
-- publishes. (Miri/Niah/Mulu/Lambir are outside the Kuching-region planner, which skips them.)
insert into public.locations (id, name, area, description)
values
  ('11111111-0000-0000-0000-000000000006', 'Miri', 'Miri', 'Northern Sarawak gateway to Mulu, Niah and Lambir Hills.'),
  ('11111111-0000-0000-0000-000000000007', 'Kuching Wetlands', 'Kuching', 'River-cruise wetlands near Kuching.')
on conflict (id) do nothing;

insert into public.attractions
  (name, slug, summary, description, location_id, avg_visit_minutes, price_min, price_max, is_free, booking_required, tips, is_published, featured_rank)
values
  ('Gunung Mulu National Park', 'gunung-mulu-national-park',
   'UNESCO World Heritage site: caves, canopy walks and the bat exodus at sunset.',
   'DRAFT — confirm details before publishing. Caves, canopy walks and the famous bat exodus at sunset. A UNESCO World Heritage site near Miri.',
   '11111111-0000-0000-0000-000000000006', 480, 0, 0, false, true, 'Book ahead — it needs planning.', false, 2),
  ('Niah Caves', 'niah-caves',
   'Ancient limestone caves with cave paintings.',
   'DRAFT — confirm details before publishing. Ancient limestone caves and cave paintings near Miri.',
   '11111111-0000-0000-0000-000000000006', 240, 0, 0, false, false, 'Wear grippy shoes.', false, 4),
  ('Lambir Hills National Park', 'lambir-hills-national-park',
   'Family-friendly hike with waterfalls and a swim spot.',
   'DRAFT — confirm details before publishing. A family-friendly hike to waterfalls with a place to swim, near Miri.',
   '11111111-0000-0000-0000-000000000006', 240, 0, 0, false, false, null, false, 7),
  ('Kuching Wetlands', 'kuching-wetlands',
   'Dolphin river cruise: Irrawaddy dolphins, crocodiles and monkeys.',
   'DRAFT — confirm details before publishing. A river cruise to spot Irrawaddy dolphins, crocodiles and monkeys. Entry is around RM10.',
   '11111111-0000-0000-0000-000000000007', 150, 10, 10, false, false, null, false, 8)
on conflict (slug) do update set featured_rank = excluded.featured_rank;
