// Generates supabase/seed-guide.sql from data/eateries.json (+ the must-see ranks):  npm run seed:guide
// The SQL is idempotent: safe to run again after editing the JSON (it updates by slug).
// Apply it to a project with the SQL editor / `supabase db query`, or through the Supabase MCP.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const { eateries } = JSON.parse(readFileSync(join(process.cwd(), "data", "eateries.json"), "utf8"));
const q = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const arr = (xs) => `array[${xs.map(q).join(", ")}]::text[]`;

const rows = eateries.map(
  (e, i) =>
    `  (${q(e.slug)}, ${q(e.name)}, ${q(e.city)}, ${arr(e.dishes)}, ${e.tier ?? "null"}, ${e.splurge ? "true" : "false"}, ${q(e.maps)}, ${q(e.notes)}, ${i})`,
);

const sql = `-- Generated by scripts/seed-guide.mjs from data/eateries.json — do not edit by hand.
-- Local food guide + the must-see ranking. Idempotent.

insert into public.eateries (slug, name, city, dishes, price_tier, is_splurge, maps_url, notes, sort_order)
values
${rows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name, city = excluded.city, dishes = excluded.dishes, price_tier = excluded.price_tier,
  is_splurge = excluded.is_splurge, maps_url = excluded.maps_url, notes = excluded.notes,
  sort_order = excluded.sort_order;

-- Must-see ranking (1-5 "must-see", 6-8 "also great"). Only rows that exist are ranked.
update public.attractions a
set featured_rank = v.rank
from (values
  ('semenggoh-nature-reserve', 1),
  ('gunung-mulu-national-park', 2),
  ('sarawak-cultural-village', 3),
  ('niah-caves', 4),
  ('bako-national-park', 5),
  ('kuching-waterfront', 6),
  ('lambir-hills-national-park', 7),
  ('kuching-wetlands', 8)
) as v(slug, rank)
where a.slug = v.slug;

-- Places the guide lists that we don't have full details for yet. Created as UNPUBLISHED drafts
-- with only what the guide says — an admin adds photos, price, hours and visit length, then
-- publishes. (Miri/Niah/Mulu/Lambir are outside the Kuching-region planner, which skips them.)
insert into public.locations (id, name, area, description)
values
  ('11111111-0000-0000-0000-000000000006', 'Miri', 'Miri', 'Northern Sarawak gateway to Mulu, Niah and Lambir Hills.'),
  ('11111111-0000-0000-0000-000000000007', 'Kuching Wetlands', 'Kuching', 'River-cruise wetlands near Kuching.')
on conflict (id) do nothing;

insert into public.attractions
  (name, slug, summary, description, location_id, avg_visit_minutes, price_min, price_max, is_free, booking_required, tips, is_published, featured_rank)
values
  ('Gunung Mulu National Park', 'gunung-mulu-national-park',
   'UNESCO World Heritage site: caves, canopy walks and the bat exodus at sunset.',
   'DRAFT — confirm details before publishing. Caves, canopy walks and the famous bat exodus at sunset. A UNESCO World Heritage site near Miri.',
   '11111111-0000-0000-0000-000000000006', 480, 0, 0, false, true, 'Book ahead — it needs planning.', false, 2),
  ('Niah Caves', 'niah-caves',
   'Ancient limestone caves with cave paintings.',
   'DRAFT — confirm details before publishing. Ancient limestone caves and cave paintings near Miri.',
   '11111111-0000-0000-0000-000000000006', 240, 0, 0, false, false, 'Wear grippy shoes.', false, 4),
  ('Lambir Hills National Park', 'lambir-hills-national-park',
   'Family-friendly hike with waterfalls and a swim spot.',
   'DRAFT — confirm details before publishing. A family-friendly hike to waterfalls with a place to swim, near Miri.',
   '11111111-0000-0000-0000-000000000006', 240, 0, 0, false, false, null, false, 7),
  ('Kuching Wetlands', 'kuching-wetlands',
   'Dolphin river cruise: Irrawaddy dolphins, crocodiles and monkeys.',
   'DRAFT — confirm details before publishing. A river cruise to spot Irrawaddy dolphins, crocodiles and monkeys. Entry is around RM10.',
   '11111111-0000-0000-0000-000000000007', 150, 10, 10, false, false, null, false, 8)
on conflict (slug) do update set featured_rank = excluded.featured_rank;
`;

writeFileSync(join(process.cwd(), "supabase", "seed-guide.sql"), sql);
console.log(`supabase/seed-guide.sql written (${eateries.length} eateries).`);
